(cl:defpackage caros_sensor_msgs-msg
  (:use )
  (:export
   "<TACTILEARRAYDATA>"
   "TACTILEARRAYDATA"
   "<POSESENSORSTATE>"
   "POSESENSORSTATE"
   "<TACTILEARRAYSTATE>"
   "TACTILEARRAYSTATE"
   "<BUTTONSENSORSTATE>"
   "BUTTONSENSORSTATE"
  ))

