(cl:defpackage caros_common_msgs-srv
  (:use )
  (:export
   "EMPTYSRV"
   "<EMPTYSRV-REQUEST>"
   "EMPTYSRV-REQUEST"
   "<EMPTYSRV-RESPONSE>"
   "EMPTYSRV-RESPONSE"
   "CONFIGBOOL"
   "<CONFIGBOOL-REQUEST>"
   "CONFIGBOOL-REQUEST"
   "<CONFIGBOOL-RESPONSE>"
   "CONFIGBOOL-RESPONSE"
   "CONFIGINT"
   "<CONFIGINT-REQUEST>"
   "CONFIGINT-REQUEST"
   "<CONFIGINT-RESPONSE>"
   "CONFIGINT-RESPONSE"
  ))

